#####################################################################################
# Title: Dissolve GAUL Districts and Overlay with CRP Layers
# Date: September 2013
# Project:  HarvestChoice, CRP Mapping
# Author: Bacou, Melanie <mel@mbacou.com>
#####################################################################################

setwd("/home/projects")
setwd("~/Google Drive")

library(foreign)
library(data.table)
library(rgdal)
library(rgeos)
library(maptools)
library(stringr)

# Load all ASCII documents generated by Jawoo based on the 2012 Annual Reports at
# http://www.cgiar.org/resources/crp-documents/

# Search for occurences of country names (using fuzzy matches).
# We need to remove the Reference sections first

# Load all files in a list
f <- list.files("./2013-CRP/data")
f <- lapply(f, function(x) readLines(file(x)))
